language: node_js
node_js:
  - 12
before_script:
  - npm i -g npm@6.12
branches:
  only:
  - master
  - gh-pages
install:
  - npm install
build:
  - gatsby build
deploy:
  provider: pages
  local_dir: public/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  fqdn: perspectilt.js.org
  on:
    branch: master